apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    clusterType:
    app: smesh-with-vms-usecase
  name: placement-smesh-with-vms-usecase
  namespace: openshift-gitops
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - "OpenShift"
