apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: federation
    apps.open-cluster-management.io/git-path: use-cases/smesh-with-vms/infra/
    apps.open-cluster-management.io/reconcile-option: merge
  name: smesh-with-vms-usecase-infra
  namespace: openshift-gitops
  labels:
    usecase: smesh-with-vms-usecase
    app.kubernetes.io/part-of: smesh-with-vms-usecase
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: openshift-gitops/smesh-with-vms-usecase
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-smesh-with-vms-usecase
