apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-openshift-servicemesh
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      vendor: "OpenShift"
  remediationAction: enforce
policies:
  - name: install-openshift-servicemesh
    manifests:
      - path: istio-namespace.yaml
      - path: openshift-servicemesh-subscription.yaml
