bases:
  - ../../base
resources:
  - serviceaccount-job.yaml
  - clusterrolebindinging-job.yaml
  - smesh-with-vms-infra-postsyncjob.yaml
patchesJson6902:
  - path: patches/patch-generatename.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: smesh-with-vms-infra-postsync
