apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-traffic-generator-image
policyDefaults:
  namespace: traffic-generator
  placement:
    clusterSelectors:
      vendor: "OpenShift"
  remediationAction: enforce
policies:
  - name: install-traffic-generator-image
    manifests:
      - path: ../../base/buildconfig.yaml
      - path: ../../base/imagestream.yaml
      - path: ../../base/rolebinding.yaml
