apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: smesh-with-vms-usecase
  namespace: openshift-gitops
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: usecase
        operator: In
        values:
          - smesh-with-vms-usecase
