resources:
  - channel.yaml
  - subscription-app.yaml
  - subscription-infra.yaml
  - subscription-traffic.yaml
  - application.yaml
  - placementrule.yaml

#Policies required for this use case
#generators:
#  - policy-generator-config.yaml

#Update Github URL
patches:
  - patch: |-
      - op: replace
        path: /spec/pathname
        value: https://github.com/sa-ne/servicemesh-demos.git
    target:
      kind: Channel
  - patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1git-branch
        value: main
    target:
      kind: Subscription
