apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: use-case-1-namespace
  namespace: openshift-gitops
spec:
  destination:
    namespace: use-case-namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: use-case-1/base/argo-use-case-namespace
    repoURL: https://github.com/sa-ne/servicemesh-demos.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
