kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ubi8-nc
  namespace: traffic-generator
  labels:
    app: ubi8-nc
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "ubi8-nc:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/sa-ne/servicemesh-demos.git"
      ref: main
    contextDir: /traffic-image-build/base
  triggers:
    - type: ConfigChange
  runPolicy: Serial
