apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: deploy/upstream/quickstart
    apps.open-cluster-management.io/reconcile-option: merge
  name: olm-app-policy-subscription
  namespace: policies
  labels:
    app: olm-app-policy
    app.kubernetes.io/part-of: olm-app-policy
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: policies/olm-app-policy
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-install-olm-non-openshift