apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: <cluster_name>-mesh
  namespace: <cluster_name>-system
spec:
  version: v2.1
  runtime:
    defaults:
      container:
        imagePullPolicy: Always
  gateways:
    additionalEgress:
      egress-local-cluster:
        enabled: true
        requestedNetworkView:
          - local-cluster
        routerMode: sni-dnat
        service:
          metadata:
            labels:
              federation.maistra.io/egress-for: egress-local-cluster
          ports:
            - port: 15443
              name: tls
            - port: 8188
              name: http-discovery
    additionalIngress:
      ingress-local-cluster:
        enabled: true
        routerMode: sni-dnat
        service:
          type: LoadBalancer
          metadata:
            labels:
              federation.maistra.io/ingress-for: ingress-local-cluster
          ports:
            - port: 15443
              name: tls
            - port: 8188
              name: https-discovery
  security:
    trust:
      domain: <cluster_name>.local
