bases:
  - ../../base
resources:
  - ./smesh-with-vms-app-presyncjob.yaml
  - ./bookinfo-application.yaml
#  - ./bookinfo-networking-destination-rule.yaml
  - ./bookinfo-networking-gateway.yaml
  - ./smesh-with-vms-app-postsyncjob.yaml
#https://github.com/argoproj/argo-cd/issues/1639#issuecomment-1004398142
# patchesJson6902:
#   - path: patches/patch-generatename.yaml
#     target:
#       group: batch
#       version: v1
#       kind: Job
#       name: smesh-with-vms-app-postsync
#   - path: patches/patch-generatename.yaml
#     target:
#       group: batch
#       version: v1
#       kind: Job
#       name: smesh-with-vms-app-presync
